const express = require("express");
const verifyProof = require("../utils/verifyProof");
//const MerkleTree = require("../utils/MerkleTree"); // Used for testing

const port = 1225;

const app = express();
app.use(express.json());

// Hardcode a merkle root here representing the whole 'nice list'
// paste the hex string in here, without the 0x prefix
const MERKLE_ROOT =
  "ddd59a2ffccddd60ff47993312821cd57cf30f7f14fb82937ebe2c4dc78375aa";

/*
Next items can be used for testing the server index.js file alone
- const name = "Norman Block"; <- should be sent from client
- const index = niceList.findIndex((n) => n === name); <- used to find index for provided name
- const index = 8 <- index for Norman
- const proof = merkleTree.getProof(index); <- should be sent from client
- const proofResult = verifyProof(proof, name, MERKLE_ROOT);
- console.log(proofResult);
*/

app.post("/gift", (req, res) => {
  // grab the parameters from the front-end here
  const body = req.body;
  /* 
  expects to receive the name to be verified and a proof generated by the client
  format provided is an array with two entries 
  */

  let isInTheList = false;
  const giftList = ["robot", "airplane", "boat", "doll"]; // list of gifts
  const gift = giftList[Math.floor(Math.random() * 4)]; // select random gift

  // Takes the info from the client and the MERKLE_ROOT and verifies if the client provide name is in the "nice list" for a gift.
  isInTheList = verifyProof(body.proof, body.name, MERKLE_ROOT);

  if (isInTheList) {
    res.send(body.name + ", you got a toy " + gift + "!");
  } else {
    res.send(body.name + ", you are not on the list :(");
  }
});

app.listen(port, () => {
  console.log(`Listening on port ${port}!`);
});
